const DEFAULT_GITHUB_TOKEN = process.env.GITHUB_TOKEN
const DEFAULT_REPOSITORY_NAME = process.env.REPOSITORY_NAME
const DEFAULT_LABEL_ACTION = process.env.LABEL_ACTION
const DEFAULT_LABEL = process.env.LABEL

module.exports = {
  DEFAULT_GITHUB_TOKEN,
  DEFAULT_LABEL,
  DEFAULT_LABEL_ACTION,
  DEFAULT_REPOSITORY_NAME,
}
