name: tf-labeler
author: Typeform
description: Helps you add and remove labels of all PRs in a given repo.
inputs:
  github-token:
    description: the github API token
    required: true
  repository-name:
    description: the name of the repository over which the action needs to be ran
    required: true
  label-action:
    description: add or remove the specified label
    required: true
  label:
    description: the label name to add or remove
    required: true
  base-branch:
    description: filter pulls by base branch name
    required: false
    default: all
  hard-failure:
    description: boolean, if true, fails the build on any error. If false, throws an warning instead.
    required: false

runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'tag'
  color: 'green'

