on:
  push:
  pull_request:
    branches:
      - master
jobs:
  test-labeler:
    runs-on: ubuntu-latest
    name: test-labeler
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: labeler
        uses: ./
        id: labeler
        with:
          github-token: ${{ secrets.labeler_github_token }}
          repository-name: ${{ github.repository }}
          label_action: add
          label: LABELER_TEST
